apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-java-app-deployment
  namespace: uat
  labels:
    app: my-java-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-java-app
  template:
    metadata:
      labels:
        app: my-java-app
    spec:
      containers:
      - name: my-java-app
        image: backendservices151.azurecr.io/java/java-v1:latest  # Your image path
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: acr-secret  # Reference to the secret for pulling images from ACR
